(()=>{
  'use strict';
  const BASE='https://yruaygqlsyecefrassqc.supabase.co/functions/v1',WEALTH=`${BASE}/wealth-dashboard`,$=id=>document.getElementById(id);
  const money=(v,c='USD')=>{const n=Number(v);if(!Number.isFinite(n))return '—';try{return new Intl.NumberFormat(undefined,{style:'currency',currency:c,maximumFractionDigits:0}).format(n)}catch{return `$${Math.round(n).toLocaleString()}`}};
  const pct=(v,d=1)=>{const n=Number(v);return Number.isFinite(n)?`${n.toFixed(d)}%`:'—'};
  const set=(id,v)=>{const e=$(id);if(e)e.textContent=v};
  const esc=v=>window.Nexus?.escapeHtml?Nexus.escapeHtml(v):String(v??'');
  function notice(html,kind=''){const e=$('notice');if(!e)return;e.className=`notice ${kind}`.trim();e.innerHTML=html;e.hidden=false}
  function domains(b){const grid=$('domainGrid');if(!grid)return;const allowed=(b?.domains||[]).filter(d=>!['core','experience'].includes(d.domain_key));const order=['wealth','trade','treasury','simulation','defi','global_capital_discovery','financial_planning','real_estate','retirement','tokenomics','trust','company','control'];allowed.sort((a,b)=>order.indexOf(a.domain_key)-order.indexOf(b.domain_key));grid.innerHTML=allowed.map(d=>{const m=Nexus.meta[d.domain_key]||{label:d.domain_name||d.domain_key,href:`/domain.html?domain=${encodeURIComponent(d.domain_key)}`,copy:'Authorized Life Pursuits domain.',icon:'•'};return `<a class="nexus-domain-card" href="${m.href}"><div><div class="domain-title">${esc(m.icon)} ${esc(m.label)}</div><div class="domain-copy">${esc(m.copy)}</div></div><div class="domain-meta"><span><i class="nexus-state"></i>${esc(d.access_level||'READ')}</span><span>Open →</span></div></a>`}).join('')||'<div class="notice warn">No user-facing domains are currently granted.</div>'}
  function renderWealth(w){const s=w.summary||{},c=s.reporting_currency||'USD';set('nw',money(s.net_worth,c));set('assets',money(s.total_assets,c));set('debt',`${money(s.total_debt,c)} debt`);set('nwDelta',Number.isFinite(Number(s.latest_net_worth_change_pct))?`${Number(s.latest_net_worth_change_pct)>=0?'+':''}${Number(s.latest_net_worth_change_pct).toFixed(2)}% latest change`:'Latest change unavailable');set('m5',pct(s.progress_to_5m_pct));if($('m5bar'))$('m5bar').style.width=`${Math.max(0,Math.min(100,Number(s.progress_to_5m_pct)||0))}%`;set('quality',s.dashboard_quality_state||s.quality_status||'—');set('sync',s.sync_health_state||'—');set('ownership',pct(s.ownership_coverage_pct));set('history',w.historyReadiness?.supports_30d?'30-day ready':w.historyReadiness?.supports_7d?'7-day ready':w.historyReadiness?.supports_1d?'1-day ready':'Building history');const rows=(w.allocation||[]).slice(0,7),alloc=$('allocation');if(alloc)alloc.innerHTML=rows.length?rows.map(r=>`<div class="alloc-row"><div class="alloc-name">${esc(r.asset_class||'Other')}</div><div class="bar"><span style="width:${Math.max(0,Math.min(100,Number(r.allocation_pct)||0))}%"></span></div><div class="alloc-pct">${pct(r.allocation_pct)}</div></div>`).join(''):'<div class="status-line"><span class="dot warn"></span>No allocation data available.</div>';document.querySelectorAll('.skeleton').forEach(e=>e.classList.remove('skeleton'))}
  function renderSignals(events){const host=$('overviewSignals');if(!host)return;let rows=Array.isArray(events)?events.slice():[];if(Nexus.state.preferences['experience.ribbon.platform_events']===false)rows=rows.filter(e=>String(e.domain).toLowerCase()!=='platform');if(Nexus.state.preferences['experience.ribbon.intensity']==='high_signal')rows=rows.filter(e=>Number(e.priority||0)>=88);rows=rows.slice(0,4);host.innerHTML=rows.length?rows.map(e=>`<a class="nexus-signal ${esc(e.tone||'')}" href="${esc(e.href||'#')}"><div class="d">${esc(e.domain||'Nexus')}</div><div><div class="x">${esc(e.title||'Material event')}</div><div class="m">${esc(e.detail||'Open for context')}</div></div><div class="val">${esc(e.value||'Open →')}</div></a>`).join(''):'<div class="nexus-domain-callout"><strong>No material cross-domain signal right now</strong><p>The ribbon contract is healthy; nothing currently meets your selected significance level.</p></div>'}
  async function domainSummary(key,b){const q=new URLSearchParams({op:'domain',domain:key,household_id:b.household.id});return Nexus.request(`${Nexus.EXPERIENCE}?${q}`)}
  async function platformSummary(b){const q=new URLSearchParams({op:'platform',household_id:b.household.id});return Nexus.request(`${Nexus.EXPERIENCE}?${q}`)}
  function pulseCard(key,data,b){const c=b.household?.base_currency||'USD',m=data?.metrics||{},r=data?.recent||[],meta=Nexus.meta[key]||{label:key};if(key==='treasury')return {t:'Treasury',v:m.approval_required?`${m.approval_required} approval${m.approval_required===1?'':'s'}`:`${m.recommendation_count||0} active`,s:'Governed recommendations',tone:m.approval_required?'warn':''};if(key==='trade')return {t:'Trade',v:`${m.execution_count||0} executions`,s:`${m.verified_count||0} verified in returned window`,tone:''};if(key==='retirement')return {t:'Retirement',v:Number.isFinite(Number(m.readiness_score))?`${Number(m.readiness_score).toFixed(0)}/100`:'—',s:String(m.runway_state||m.stage_code||'Current state'),tone:Number(m.readiness_score)>=80?'good':''};if(key==='real_estate')return {t:'Real Estate',v:money(m.total_property_equity,c),s:`${m.property_count||0} properties · equity`,tone:''};if(key==='simulation')return {t:'Simulation',v:money(m.projected_value,c),s:`${m.projected_position_count||0} projected positions`,tone:''};if(key==='defi')return {t:'DeFi',v:`${m.capability_count||0} capabilities`,s:`${m.new_count||0} newly surfaced`,tone:m.new_count?'warn':''};if(key==='financial_planning')return {t:'Planning',v:money(m.investable_assets,c),s:'Investable assets in planning model',tone:''};if(key==='tokenomics')return {t:'Tokenomics',v:`${m.asset_count||0} assets`,s:`${m.healthy_supply_count||0} supply states healthy`,tone:''};if(key==='global_capital_discovery')return {t:'Discovery',v:`${m.subject_count||0} subjects`,s:`${m.total_signals||0} supporting signals`,tone:''};if(key==='trust')return {t:'Trust',v:`${m.trust_count||0} trusts`,s:'Governance and funding state',tone:''};if(key==='company')return {t:'Company',v:`${m.company_count||0} companies`,s:`${m.open_compliance_items||0} open compliance items`,tone:m.open_compliance_items?'warn':''};return {t:meta.label,v:`${r.length} records`,s:'Authorized current view',tone:''}}
  function platformPulse(data){const o=data?.health?.overall||{},state=String(o.overall_health||'UNKNOWN').toUpperCase();return {t:'Platform',v:state,s:`${o.attention_count||0} attention · ${o.maturing_count||0} maturing`,tone:state==='HEALTHY'?'good':'warn'}}
  function priorityKeys(){const mode=String(Nexus.state.preferences['experience.overview.mode']||'balanced');const map={balanced:['treasury','trade','retirement','real_estate','control','simulation','defi'],capital:['real_estate','retirement','financial_planning','treasury','simulation','control'],intelligence:['trade','treasury','defi','tokenomics','global_capital_discovery','control']};return (map[mode]||map.balanced).filter(k=>Nexus.hasDomain(k)).slice(0,5)}
  async function renderPulse(b){const keys=priorityKeys(),host=$('overviewPulse');if(!keys.length){host.innerHTML='<div class="nexus-domain-callout"><strong>No priority domains enabled</strong><p>Nexus will expand this pulse as domain grants are added.</p></div>';return}const settled=await Promise.allSettled(keys.map(k=>k==='control'?platformSummary(b):domainSummary(k,b)));host.innerHTML=settled.map((res,i)=>{const key=keys[i],card=res.status==='fulfilled'?(key==='control'?platformPulse(res.value):pulseCard(key,res.value,b)):{t:Nexus.meta[key]?.label||key,v:'Unavailable',s:'Secure summary did not load',tone:'warn'};return `<a class="nexus-pulse-card ${esc(card.tone||'')}" href="${esc(Nexus.workspaceHref(key))}"><div class="t">${esc(card.t)}</div><div class="v">${esc(card.v)}</div><div class="s">${esc(card.s)}</div></a>`}).join('')}
  function singleWealthMode(){set('overviewHeadline','Wealth');set('overviewCopy','Net worth, assets, liabilities, allocation and data readiness.');for(const id of ['overviewPulse','overviewSignals','domainGrid']){const e=$(id);if(e){e.hidden=true;if(e.previousElementSibling?.classList.contains('nexus-section-head'))e.previousElementSibling.hidden=true}}const title=document.querySelector('.page-title');if(title)title.textContent='Wealth';const sub=document.querySelector('.page-sub');if(sub)sub.textContent='Capital, ownership and financial position'}
  function maybeRedirect(){const single=Nexus.singleDomainKey?.();if(single&&single!=='wealth'){location.replace(Nexus.workspaceHref(single));return true}if(single==='wealth'){singleWealthMode();return false}const q=new URLSearchParams(location.search);if(q.get('stay')==='overview')return false;const key=String(Nexus.state.preferences['experience.default_workspace']||'overview');if(key==='overview'||!Nexus.hasDomain(key))return false;location.replace(Nexus.workspaceHref(key));return true}
  async function load(b){domains(b);if(maybeRedirect())return;const badge=$('securityBadge');if(badge){badge.textContent='Secure · NEXUS';badge.className='badge secure'};const h=b.household;if(h)set('nexusAsOf',`${h.name||'Household'} · ${h.base_currency||'USD'}`);if(!Nexus.singleDomainKey?.()){renderSignals(b.ribbon||[]);window.addEventListener('nexus:ribbon',e=>renderSignals(e.detail||[]));renderPulse(b).catch(e=>console.warn('Cross-domain pulse unavailable',e))}if(!Nexus.hasDomain('wealth')){set('nw','—');set('overviewHeadline','Your authorized domains, one decision surface.');set('overviewCopy','Wealth is not enabled for this principal; Nexus is composing only the domains you are authorized to use.');document.querySelectorAll('.skeleton').forEach(e=>e.classList.remove('skeleton'));return}try{const q=new URLSearchParams({household_id:b.household.id});renderWealth(await Nexus.request(`${WEALTH}?${q}`))}catch(e){console.error(e);notice('<strong>Wealth data is temporarily unavailable.</strong> Other authorized Nexus domains remain available.','warn')}}
  async function start(){try{const b=await Nexus.start();await load(b)}catch(e){console.error(e);const badge=$('securityBadge');if(badge){badge.textContent='Sign-in required';badge.className='badge warn'};notice('<strong>Secure Nexus access required.</strong> <a href="/login.html">Sign in</a> to establish an authorized session.','warn')}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start()
})();