(()=>{
  'use strict';
  const API_URL='https://yruaygqlsyecefrassqc.supabase.co/functions/v1/attention-center-api';
  const $=id=>document.getElementById(id),badge=$('securityBadge'),list=$('attentionList'),filters=$('filters'),inbox=$('inboxView'),detail=$('detailView'),toast=$('toast');
  let rows=[],active='All',apiCache=new Map();
  const esc=v=>String(v??'').replace(/[&<>\'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  async function token(){if(!window.lifePursuitsAuth?.getAccessToken)throw new Error('ACCESS_BOUNDARY_UNAVAILABLE');const t=await window.lifePursuitsAuth.getAccessToken({forceBoundary:true});if(!t)throw new Error('AUTH_REQUIRED');return t}
  async function loadLive(){const t=await token();const r=await fetch(API_URL,{method:'GET',headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json'},cache:'no-store',credentials:'omit',referrerPolicy:'no-referrer'});const b=await r.json().catch(()=>({}));if(!r.ok){if(r.status===401||r.status===403)window.lifePursuitsAuth?.clear?.();throw new Error(b.error||b.reason||`HTTP_${r.status}`)}const raw=Array.isArray(b.items)?b.items:[];rows=normalize(raw);apiCache=new Map(raw.map((x,i)=>[String(x.id||x.candidate_id||x.approval_packet_id||`live-${i}`),x]));return rows}
  async function respond(itemId,action){const item=apiCache.get(String(itemId));if(!item?.request_id)throw new Error('NO_DECISION_REQUEST');if(Array.isArray(item.allowed_actions)&&item.allowed_actions.length&&!item.allowed_actions.includes(String(action).toUpperCase()))throw new Error('ACTION_NOT_ALLOWED');const t=await token();const r=await fetch(API_URL,{method:'POST',headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json'},body:JSON.stringify({request_id:item.request_id,action}),cache:'no-store',credentials:'omit',referrerPolicy:'no-referrer'});const b=await r.json().catch(()=>({}));if(!r.ok){if(r.status===401||r.status===403)window.lifePursuitsAuth?.clear?.();throw new Error(b.error||b.reason||`HTTP_${r.status}`)}return b}
  const friendly={P5:'Capability Update',WCD:'Opportunity Discovery',GCD:'Opportunity Discovery','WCD / GCD':'Opportunity Discovery',HEALTH:'System Health',PLATFORM:'System Health'};
  const formatConfidence=v=>typeof v==='number'?(v<=1?`${Math.round(v*100)}%`:`${Math.round(v)}%`):(v||'—');
  const formatTime=v=>{if(!v)return '';const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleString([], {month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})};
  const formatExpiry=v=>{if(!v)return '—';const d=new Date(v);if(Number.isNaN(d.getTime()))return String(v);const ms=d-Date.now();if(ms<=0)return 'Expired';const min=Math.round(ms/60000);if(min<60)return `${min} min remaining`;const hrs=Math.round(min/60);if(hrs<48)return `${hrs} hr remaining`;return d.toLocaleString()};
  function normalize(raw){return raw.map((r,i)=>{const internal=String(r.internal_domain||r.domain||r.domain_key||'Attention');const provider=r.provider||r.provider_key||r.protocol||r.app_name||r.source_name||'';let domain=r.user_category||r.notification_type||r.domain||friendly[internal]||internal;if(internal==='P5'&&/new.?capability/i.test(String(r.event_type||r.title||domain)))domain='New Capability';return{id:String(r.id||r.candidate_id||r.approval_packet_id||`live-${i}`),allowed_actions:r.allowed_actions||[],domain,provider,severity:r.severity_label||r.severity||'INFO',level:r.level||((r.actionability==='approve'||r.actionability==='decide')?'action':'watch'),title:r.user_title||r.title||'Update needs review',description:r.user_summary||r.description||r.summary||'Open for details.',time:formatTime(r.time||r.occurred_at),expiry:r.expiry||r.valid_until||'',health:r.health||r.health_state||'UNKNOWN',confidence:formatConfidence(r.confidence_display||r.confidence),risk:r.risk||r.risk_level||'—',proposed:r.proposed||r.proposed_action||'',benefit:r.benefit||r.expected_benefit||'',risks:r.risks||r.key_risks||'',rationale:r.rationale||'',context:r.context||r.decision_context||'',accent:r.accent||'#2f81f7',icon:r.icon||String(domain).slice(0,1).toUpperCase()}})}
  function counts(){$('actionCount').textContent=rows.filter(r=>r.level==='action').length;$('watchCount').textContent=rows.filter(r=>r.level==='watch').length;$('infoCount').textContent=rows.filter(r=>r.level==='info').length;$('totalCount').textContent=rows.length}
  function renderFilters(){const domains=['All',...Array.from(new Set(rows.map(r=>r.domain)))];filters.innerHTML=domains.map(d=>`<button class="chip ${d===active?'active':''}" data-filter="${esc(d)}">${esc(d)}</button>`).join('');filters.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{active=b.dataset.filter;renderFilters();renderList()})}
  function renderList(){const visible=active==='All'?rows:rows.filter(r=>r.domain===active);if(!visible.length){list.innerHTML='<div class="empty-state">Nothing currently requires attention in this view.</div>';return}list.innerHTML=visible.map(r=>`<article class="item" data-id="${esc(r.id)}" style="--accent:${esc(r.accent)}"><div class="item-top"><div class="icon">${esc(r.icon)}</div><div class="domain">${esc(r.domain)}</div>${r.provider?`<span class="pill low">${esc(r.provider)}</span>`:''}<span class="pill ${esc(String(r.severity).toLowerCase())}">${esc(r.severity)}</span><div class="time">${esc(r.time)}</div></div><div class="title">${esc(r.title)}</div><div class="desc">${esc(r.description)}</div><div class="expiry">${esc(formatExpiry(r.expiry))}</div><div class="chev">›</div></article>`).join('');list.querySelectorAll('[data-id]').forEach(el=>el.onclick=()=>openDetail(el.dataset.id))}
  function openDetail(id){const r=rows.find(x=>String(x.id)===String(id));if(!r)return;$('detailIcon').textContent=r.icon;$('detailIcon').style.background=r.accent;$('detailDomain').textContent=r.provider?`${r.domain} · ${r.provider}`:r.domain;$('detailTime').textContent=r.time;$('detailSeverity').textContent=r.severity;$('detailSeverity').className=`pill ${String(r.severity).toLowerCase()}`;$('detailTitle').textContent=r.title;$('detailDesc').textContent=r.description;$('healthMetric').textContent=`System: ${r.health}`;$('confidenceMetric').textContent=`Confidence: ${r.confidence}`;$('riskMetric').textContent=`Risk: ${r.risk}`;$('detailFacts').innerHTML=`${r.provider?`<div class="k">Source</div><div class="v">${esc(r.provider)}</div>`:''}<div class="k">What you can do</div><div class="v">${esc(r.proposed||'Review this item')}</div><div class="k">Potential benefit</div><div class="v">${esc(r.benefit||'—')}</div><div class="k">What to consider</div><div class="v">${esc(r.risks||'—')}</div><div class="k">Why you received this</div><div class="v">${esc(r.rationale||'—')}</div><div class="k">Timing</div><div class="v">${esc(formatExpiry(r.expiry))}</div>`;$('detailContext').textContent=r.context||'—';document.querySelectorAll('.action').forEach(b=>{b.dataset.itemId=r.id;b.disabled=Array.isArray(r.allowed_actions)&&r.allowed_actions.length>0&&!r.allowed_actions.includes(b.dataset.action)});inbox.classList.add('hidden');detail.classList.add('open');window.scrollTo({top:0,behavior:'smooth'})}
  function back(){detail.classList.remove('open');inbox.classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})}
  function showToast(msg){toast.textContent=msg;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),3000)}
  async function doAction(button){const action=button.dataset.action,itemId=button.dataset.itemId;button.disabled=true;try{const result=await respond(itemId,action);showToast(result?.message||`${action} recorded.`);await loadLive();counts();renderFilters();renderList();back()}catch(e){console.error(e);showToast(e.message==='AUTH_REQUIRED'?'Sign in is required for live actions.':`Unable to ${action.toLowerCase()} this item.`)}finally{button.disabled=false}}
  async function start(){$('backButton').onclick=back;document.querySelectorAll('.action').forEach(b=>b.onclick=()=>doAction(b));try{await loadLive();badge.textContent='Authenticated · Live';badge.className='security live'}catch(e){console.error('Attention Center live load failed',e);rows=[];badge.textContent=e.message==='AUTH_REQUIRED'?'Sign-in Required':'Live data unavailable';badge.className='security demo';showToast(e.message==='AUTH_REQUIRED'?'Sign in to load governed decisions.':'Live Attention data is unavailable; no preview decisions are being shown.')}counts();renderFilters();renderList()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start()
})();