(()=>{
  'use strict';
  const BASE='https://yruaygqlsyecefrassqc.supabase.co/functions/v1';
  const EXPERIENCE=`${BASE}/nexus-experience-api`;
  const PREFS=`${BASE}/sage-phase7-preferences`;
  const DOMAIN_META={
    wealth:{label:'Wealth',icon:'◈',href:'/?stay=overview#wealth',copy:'Net worth, assets, liabilities and ownership.'},
    trade:{label:'Trade',icon:'↗',href:'/domain.html?domain=trade',copy:'XRPL market intelligence, decisions and executions.'},
    treasury:{label:'Treasury',icon:'△',href:'/treasury-dashboard.html',copy:'Yield, capital deployment and governed recommendations.'},
    simulation:{label:'Simulation',icon:'◇',href:'/domain.html?domain=simulation',copy:'Counterfactual portfolios, scenarios and learning.'},
    defi:{label:'DeFi',icon:'⟲',href:'/domain.html?domain=defi',copy:'Protocols, capabilities, yield and reward intelligence.'},
    global_capital_discovery:{label:'Discovery',icon:'◎',href:'/domain.html?domain=global_capital_discovery',copy:'Cross-asset global capital discovery and evidence.'},
    financial_planning:{label:'Planning',icon:'▦',href:'/domain.html?domain=financial_planning',copy:'Household planning, retirement and decision context.'},
    real_estate:{label:'Real Estate',icon:'⌂',href:'/domain.html?domain=real_estate',copy:'Property value, debt, cash flow and evidence.'},
    retirement:{label:'Retirement',icon:'◷',href:'/domain.html?domain=retirement',copy:'Retirement transition, income and readiness.'},
    tokenomics:{label:'Tokenomics',icon:'⎔',href:'/domain.html?domain=tokenomics',copy:'Asset supply, unlock and token economic intelligence.'},
    trust:{label:'Trust',icon:'□',href:'/domain.html?domain=trust',copy:'Trust-owned capital and stewardship.'},
    company:{label:'Company',icon:'▣',href:'/domain.html?domain=company',copy:'Company capital and operating visibility.'},
    control:{label:'Platform',icon:'◇',href:'/platform.html',copy:'Platform health, resources and operations.'}
  };
  const USER_DOMAIN_ORDER=['wealth','trade','treasury','simulation','defi','global_capital_discovery','financial_planning','real_estate','retirement','tokenomics','trust','company'];
  const state={bootstrap:null,preferences:{},householdId:null,principalId:null,startPromise:null,refreshTimer:null};
  const escapeHtml=v=>String(v??'').replace(/[&<>\'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  async function token(){if(!window.lifePursuitsAuth?.getAccessToken)throw new Error('AUTH_REQUIRED');const t=await window.lifePursuitsAuth.getAccessToken();if(!t)throw new Error('AUTH_REQUIRED');return t}
  async function request(url,options={}){const t=await token();const r=await fetch(url,{method:options.method||'GET',headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json',...(options.headers||{})},body:options.body?JSON.stringify(options.body):undefined,cache:'no-store',credentials:'omit',referrerPolicy:'no-referrer'});const b=await r.json().catch(()=>({}));if(!r.ok){if(r.status===401)window.lifePursuitsAuth?.clear?.();const e=new Error(b.code||b.reason||b.error||`HTTP_${r.status}`);e.status=r.status;throw e}return b}
  function currentPath(){return location.pathname.toLowerCase()}
  function domainKeys(){return new Set((state.bootstrap?.domains||[]).map(d=>String(d.domain_key).toLowerCase()))}
  function hasDomain(key){return domainKeys().has(String(key).toLowerCase())}
  function userDomainKeys(){const keys=domainKeys();return USER_DOMAIN_ORDER.filter(k=>keys.has(k))}
  function singleDomainKey(){const user=userDomainKeys();return user.length===1&&!hasDomain('control')?user[0]:null}
  function selectedHousehold(){return state.bootstrap?.household||null}
  function selectedPrincipal(){return state.bootstrap?.principal||null}
  function workspaceHref(key){if(key==='overview'||!key)return '/?stay=overview';return DOMAIN_META[key]?.href||`/domain.html?domain=${encodeURIComponent(key)}`}
  function brand(){const single=singleDomainKey();return `<a href="${escapeHtml(single?workspaceHref(single):'/?stay=overview')}" class="brand-lockup" aria-label="Nexus Life Pursuits"><span class="brand-nexus">NEXUS</span><span class="brand-life">Life Pursuits</span></a>`}
  function navItems(){const keys=domainKeys(),single=singleDomainKey();if(single)return [{...DOMAIN_META[single],key:single}];const out=[{label:'Overview',icon:'⌂',href:'/?stay=overview',key:'overview'}];USER_DOMAIN_ORDER.forEach(k=>{if(keys.has(k))out.push({...DOMAIN_META[k],key:k})});out.push({label:'Attention',icon:'!',href:'/approval-center.html',key:'attention'});out.push({label:'Connections',icon:'⇄',href:'/connections.html',key:'connections'});out.push({label:'Preferences',icon:'⚙',href:'/preferences.html',key:'preferences'});if(keys.has('control'))out.push({...DOMAIN_META.control,key:'control'});return out}
  function isActive(item){const path=currentPath(),root=path==='/'||path==='/index.html';if(item.key==='overview')return root&&location.hash!=='#wealth';if(item.key==='wealth'&&root)return location.hash==='#wealth';if(item.key&&path==='/domain.html')return new URLSearchParams(location.search).get('domain')===item.key;return path===item.href.split('?')[0].split('#')[0]}
  function renderNavigation(){document.querySelectorAll('.sidebar .brand').forEach(e=>e.innerHTML=brand());const items=navItems();document.querySelectorAll('.nav-list').forEach(nav=>{nav.innerHTML=items.map(i=>`<a class="nav-link${isActive(i)?' active':''}" href="${i.href}">${i.icon?`<span class="nav-icon">${escapeHtml(i.icon)}</span>`:''}${escapeHtml(i.label)}</a>`).join('')});document.querySelectorAll('.mobile-nav').forEach(nav=>{const single=singleDomainKey();if(single){const i=items[0];nav.innerHTML=`<a class="${isActive(i)?'active':''}" href="${i.href}"><span class="i">${escapeHtml(i.icon||'•')}</span>${escapeHtml(i.label)}</a>`;return}const preferred=String(state.preferences['experience.mobile.pin']||'auto'),selected=[];const take=key=>{const found=items.find(i=>i.key===key||String(i.label).toLowerCase()===key);if(found&&!selected.includes(found))selected.push(found)};take('overview');if(preferred!=='auto')take(preferred);['wealth','trade','treasury','attention','simulation','defi'].forEach(take);nav.innerHTML=selected.slice(0,5).map(i=>`<a class="${isActive(i)?'active':''}" href="${i.href}"><span class="i">${escapeHtml(i.icon||'•')}</span>${escapeHtml(i.label==='Overview'?'Home':i.label)}</a>`).join('')});const p=selectedPrincipal(),h=selectedHousehold(),picker=document.getElementById('householdPicker');if(picker){const households=state.bootstrap?.households||[h].filter(Boolean);picker.innerHTML=households.map(x=>`<option value="${escapeHtml(x.id)}"${x.id===h?.id?' selected':''}>${escapeHtml(x.name||'Household')}</option>`).join('');picker.hidden=households.length<2;picker.onchange=()=>{sessionStorage.setItem('nexusHouseholdId',picker.value);location.reload()}}document.querySelectorAll('.identity-name').forEach(e=>e.textContent=p?.display_name||'Authenticated user');document.querySelectorAll('.identity-meta').forEach(e=>e.textContent=h?`${h.role||'member'} · ${h.base_currency||'USD'}`:'Secure Nexus session')}
  function filteredRibbon(events){let rows=Array.isArray(events)?events.slice():[];const single=singleDomainKey();if(single)rows=rows.filter(e=>String(e.domain||'').toLowerCase()===single);if(state.preferences['experience.ribbon.platform_events']===false)rows=rows.filter(e=>String(e.domain).toLowerCase()!=='platform');if(state.preferences['experience.ribbon.intensity']==='high_signal')rows=rows.filter(e=>Number(e.priority||0)>=88);return rows}
  function renderRibbon(events=[]){let host=document.getElementById('nexusRibbon');if(!host){const top=document.querySelector('.topbar');if(!top)return;host=document.createElement('div');host.id='nexusRibbon';host.className='nexus-ribbon';top.insertAdjacentElement('afterend',host)}if(state.preferences['experience.ribbon.enabled']===false){host.hidden=true;return}host.hidden=false;events=filteredRibbon(events);if(!events.length){host.innerHTML='<div class="nexus-ribbon-label">INTELLIGENCE</div><div class="nexus-ribbon-empty">No material intelligence right now.</div>';return}const motion=state.preferences['experience.ribbon.motion'],stationary=motion==='reduced'||window.matchMedia('(prefers-reduced-motion: reduce)').matches,style=stationary?' style="animation:none"':'';const items=events.map(e=>`<a class="nexus-ribbon-item ${escapeHtml(e.tone||'')}" href="${escapeHtml(e.href||'#')}"><span class="domain">${escapeHtml(e.domain)}</span><strong>${escapeHtml(e.title)}</strong>${e.value?`<span class="value">${escapeHtml(e.value)}</span>`:''}</a>`).join('');host.innerHTML=`<div class="nexus-ribbon-label">INTELLIGENCE</div><div class="nexus-ribbon-window"><div class="nexus-ribbon-track"${style}>${items}${!stationary&&events.length>2?items:''}</div></div>`}
  function renderContextStrip(){const q=new URLSearchParams(location.search);if(q.get('from')!=='nexus'&&!q.get('event'))return;const main=document.querySelector('main.content');if(!main||main.querySelector('.nexus-context-strip'))return;const strip=document.createElement('div');strip.className='nexus-context-strip';strip.innerHTML=`<span>Nexus context</span><strong>${escapeHtml(q.get('event')||q.get('entity')||'Cross-domain intelligence')}</strong><a href="${escapeHtml(singleDomainKey()?workspaceHref(singleDomainKey()):'/?stay=overview')}">Return</a>`;main.prepend(strip)}
  async function loadPreferences(){try{const qs=new URLSearchParams({domain:'experience',purpose:'presentation',consumer:'nexus',channel:'web'});if(state.householdId)qs.set('household_id',state.householdId);if(state.principalId)qs.set('principal_id',state.principalId);const p=await request(`${PREFS}?op=resolve&${qs}`),map={};(p.preferences||[]).forEach(x=>{map[x.preference_key]=x.value});state.preferences=map;document.body.classList.toggle('nexus-compact',map['experience.dashboard.density']==='compact')}catch(e){console.warn('Nexus preferences unavailable; defaults applied',e);state.preferences={}}}
  async function refreshRibbon(){if(document.hidden||!state.householdId)return;try{const q=new URLSearchParams({op:'ribbon',household_id:state.householdId});const b=await request(`${EXPERIENCE}?${q}`);if(state.bootstrap)state.bootstrap.ribbon=b.events||[];renderRibbon(b.events||[]);window.dispatchEvent(new CustomEvent('nexus:ribbon',{detail:b.events||[]}))}catch(e){console.warn('Nexus ribbon refresh failed',e)}}
  function scheduleRibbon(){clearInterval(state.refreshTimer);state.refreshTimer=setInterval(refreshRibbon,300000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refreshRibbon()},{passive:true})}
  function start(){if(state.startPromise)return state.startPromise;state.startPromise=(async()=>{try{if(window.lifePursuitsAuth?.bootstrapSecureAccess)await window.lifePursuitsAuth.bootstrapSecureAccess();const preferred=sessionStorage.getItem('nexusHouseholdId'),q=new URLSearchParams({op:'bootstrap'});if(preferred)q.set('household_id',preferred);const b=await request(`${EXPERIENCE}?${q}`);state.bootstrap=b;state.householdId=b.household?.id||null;state.principalId=b.principal?.id||null;if(state.householdId)sessionStorage.setItem('nexusHouseholdId',state.householdId);await loadPreferences();renderNavigation();renderRibbon(b.ribbon||[]);renderContextStrip();scheduleRibbon();window.dispatchEvent(new CustomEvent('nexus:ready',{detail:b}));return b}catch(e){state.startPromise=null;document.documentElement.dataset.nexusError=e.message;throw e}})();return state.startPromise}
  async function savePreference(key,value,options={}){return request(`${PREFS}?op=save`,{method:'POST',body:{household_id:state.householdId,principal_id:state.principalId,preference_key:key,value,domain:'experience',category:'experience',semantic_type:'EXACT',consequence_level:'LOW',purposes:['presentation'],context:{channel:'web'},...options}})}
  window.Nexus={start,request,savePreference,hasDomain,domainKeys,userDomainKeys,singleDomainKey,meta:DOMAIN_META,state,escapeHtml,workspaceHref,EXPERIENCE,PREFS};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>start().catch(()=>{}),{once:true});else start().catch(()=>{})
})();